basic_cofig:
  overwrite: True
  resume: True
  cosine: True
  backbone: resnet18
  feat_dim: 128
  lr: 0.01
  wd: 0.001
  epoch: 800
  gpu: 7
  seed: 0
  alpha_mixup: 4

moco_config:
  moco_queue: 8192
  moco_m: 0.99
  loss_weight: 0.5
  moco_t: 0.07

dataset_config:
  dataset: cifar100
  num_classes: 100
  partial_rate: 0.1
  balanced: False
  hierarchical: False

path_cofig:
  save_dir: ./saved_models
  save_name: my_cifar100_10000_01
  load_name: latest_model.pth

semi_cofig:
  warm_up: 50
  num_labels: 10000
  ratio: 7
  ema_update_confi: 0

